# Generated by Django 4.1 on 2022-09-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0006_option_auto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=30, verbose_name='Идентификационный номер (VIN)')),
                ('engine_volume', models.SmallIntegerField(verbose_name='Объем двигателя, куб.см')),
                ('engine_power', models.SmallIntegerField(verbose_name='Мощность двигателя, л.с.')),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motorpool.auto')),
            ],
            options={
                'verbose_name': 'Паспорт машины',
                'verbose_name_plural': 'Паспорта машин',
            },
        ),
    ]
