# Generated by Django 4.1 on 2022-09-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0008_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
