# Generated by Django 4.1 on 2022-09-04 10:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0009_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
                ('objects_volvo', django.db.models.manager.Manager()),
            ],
        ),
    ]
