# Generated by Django 4.1 on 2022-09-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0010_alter_auto_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auto',
            managers=[
            ],
        ),
    ]
