# Generated by Django 4.1 on 2022-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0014_alter_vehiclepassport_auto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=210),
        ),
    ]
