# Generated by Django 4.1 on 2022-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0016_alter_vehiclepassport_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='motorpool/brands'),
        ),
    ]
